# Generated by Django 5.2.1 on 2025-05-23 23:59

import django.core.validators
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "down_payment_amt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "mortgage_term_months",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(480),
                        ]
                    ),
                ),
                (
                    "total_loan_amount",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("purchase_price"),
                            "-",
                            models.F("down_payment_amt"),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2,
                            max_digits=15,
                            validators=[django.core.validators.MinValueValidator(0.0)],
                        ),
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "total_amt_paid",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "total_interest_paid",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "purchase_price",
                            "down_payment_amt",
                            "mortgage_term_months",
                        ],
                        name="mortgageapp_purchas_a4f243_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "purchase_price",
                            "down_payment_amt",
                            "mortgage_term_months",
                        ),
                        name="unique_mortgage_entry",
                    )
                ],
            },
        ),
    ]
