# Generated by Django 5.2.1 on 2025-05-24 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0003_alter_search_monthly_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="monthly_payment",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="purchase price",
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="total_amt_paid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="total_interest_paid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
