# Generated by Django 5.2.1 on 2025-05-24 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0004_alter_search_monthly_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="search",
            name="down_payment_amt",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="down payment",
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="mortgage_term_months",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(12),
                    django.core.validators.MaxValueValidator(480),
                ],
                verbose_name="mortgage term",
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="total_amt_paid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Total amount paid over the course of the loan",
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="total_interest_paid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Total interest paid over the course of the loan",
            ),
        ),
    ]
