# Generated by Django 5.2.1 on 2025-05-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mortgageapp",
            "0005_search_interest_rate_alter_search_down_payment_amt_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="search",
            name="unique_mortgage_entry",
        ),
        migrations.RemoveIndex(
            model_name="search",
            name="mortgageapp_purchas_a4f243_idx",
        ),
        migrations.AddIndex(
            model_name="search",
            index=models.Index(
                fields=[
                    "purchase_price",
                    "down_payment_amt",
                    "mortgage_term_months",
                    "interest_rate",
                ],
                name="mortgageapp_purchas_9887ae_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="search",
            constraint=models.UniqueConstraint(
                fields=(
                    "purchase_price",
                    "down_payment_amt",
                    "mortgage_term_months",
                    "interest_rate",
                ),
                name="unique_mortgage_entry",
            ),
        ),
    ]
