# Generated by Django 5.2.1 on 2025-05-24 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0007_alter_search_monthly_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="monthly_payment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="total_amt_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Total amount paid over the course of the loan",
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="total_interest_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Total interest paid over the course of the loan",
            ),
        ),
    ]
