# Generated by Django 5.2.1 on 2025-05-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0008_alter_search_monthly_payment_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="search",
            name="unique_mortgage_entry",
        ),
        migrations.RemoveIndex(
            model_name="search",
            name="mortgageapp_purchas_9887ae_idx",
        ),
        migrations.RenameField(
            model_name="search",
            old_name="mortgage_term_months",
            new_name="mortgage_term",
        ),
        migrations.AddIndex(
            model_name="search",
            index=models.Index(
                fields=[
                    "purchase_price",
                    "down_payment_amt",
                    "mortgage_term",
                    "interest_rate",
                ],
                name="mortgageapp_purchas_92071b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="search",
            constraint=models.UniqueConstraint(
                fields=(
                    "purchase_price",
                    "down_payment_amt",
                    "mortgage_term",
                    "interest_rate",
                ),
                name="unique_mortgage_entry",
            ),
        ),
    ]
