# Generated by Django 5.2.1 on 2025-05-24 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0009_remove_search_unique_mortgage_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="mortgage_term_unit",
            field=models.CharField(
                choices=[("months", "Months"), ("years", "Years")],
                default="years",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="mortgage_term",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="mortgage term",
            ),
        ),
    ]
