# Generated by Django 5.2.1 on 2025-05-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0010_search_mortgage_term_unit_alter_search_mortgage_term"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="search",
            name="unique_mortgage_entry",
        ),
        migrations.RemoveIndex(
            model_name="search",
            name="mortgageapp_purchas_92071b_idx",
        ),
        migrations.AlterField(
            model_name="search",
            name="mortgage_term_unit",
            field=models.CharField(
                choices=[("months", "Months"), ("years", "Years")],
                default="years",
                max_length=10,
                verbose_name="Choose whether you wish to enter in months or years",
            ),
        ),
        migrations.AddIndex(
            model_name="search",
            index=models.Index(
                fields=[
                    "purchase_price",
                    "down_payment_amt",
                    "mortgage_term_unit",
                    "mortgage_term",
                    "interest_rate",
                ],
                name="mortgageapp_purchas_28b179_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="search",
            constraint=models.UniqueConstraint(
                fields=(
                    "purchase_price",
                    "down_payment_amt",
                    "mortgage_term_unit",
                    "mortgage_term",
                    "interest_rate",
                ),
                name="unique_mortgage_entry",
            ),
        ),
    ]
