# Generated by Django 5.2.1 on 2025-05-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0011_remove_search_unique_mortgage_entry_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="search",
            name="total_loan_amount",
        ),
    ]
