# Generated by Django 5.2.1 on 2025-05-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0012_remove_search_total_loan_amount"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="search",
            name="unique_mortgage_entry",
        ),
        migrations.RemoveIndex(
            model_name="search",
            name="mortgageapp_purchas_28b179_idx",
        ),
        migrations.RenameField(
            model_name="search",
            old_name="down_payment_amt",
            new_name="down_payment",
        ),
        migrations.AddIndex(
            model_name="search",
            index=models.Index(
                fields=[
                    "purchase_price",
                    "down_payment",
                    "mortgage_term_unit",
                    "mortgage_term",
                    "interest_rate",
                ],
                name="mortgageapp_purchas_d600a1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="search",
            constraint=models.UniqueConstraint(
                fields=(
                    "purchase_price",
                    "down_payment",
                    "mortgage_term_unit",
                    "mortgage_term",
                    "interest_rate",
                ),
                name="unique_mortgage_entry",
            ),
        ),
    ]
