# Generated by Django 5.2.1 on 2025-05-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0013_remove_search_unique_mortgage_entry_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="search",
            name="unique_mortgage_entry",
        ),
        migrations.RemoveIndex(
            model_name="search",
            name="mortgageapp_purchas_d600a1_idx",
        ),
        migrations.AddField(
            model_name="search",
            name="down_payment_in",
            field=models.CharField(
                choices=[("percentage", "Percentage (%)"), ("amount", "Amount ($)")],
                default="amount",
                max_length=20,
                verbose_name="Enter down payment as amount or percentage",
            ),
        ),
        migrations.AddIndex(
            model_name="search",
            index=models.Index(
                fields=[
                    "purchase_price",
                    "down_payment_in",
                    "down_payment",
                    "mortgage_term_unit",
                    "mortgage_term",
                    "interest_rate",
                ],
                name="mortgageapp_purchas_7b02b9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="search",
            constraint=models.UniqueConstraint(
                fields=(
                    "purchase_price",
                    "down_payment_in",
                    "down_payment",
                    "mortgage_term_unit",
                    "mortgage_term",
                    "interest_rate",
                ),
                name="unique_mortgage_entry",
            ),
        ),
    ]
