# Generated by Django 5.2.1 on 2025-05-24 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0014_remove_search_unique_mortgage_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="total_loan_amt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Total loan amount",
            ),
        ),
    ]
