# Generated by Django 5.2.1 on 2025-05-24 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgageapp", "0015_search_total_loan_amt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="mortgage_term_unit",
            field=models.CharField(
                choices=[("months", "Months"), ("years", "Years")],
                default="years",
                max_length=10,
                verbose_name="Enter mortgage term in months or years",
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(1.0)],
                verbose_name="purchase price",
            ),
        ),
    ]
